"""empty message

Revision ID: 1b6be11e5cf2
Revises: 30156e5d1b02
Create Date: 2024-12-16 17:29:08.075315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6be11e5cf2'
down_revision: Union[str, None] = '30156e5d1b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_zone_name'), 'zone', ['zone_name'], unique=False)
    op.add_column('entries', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_entries_zone_id'), 'entries', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'entries', 'main_areas', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_index(op.f('ix_entries_zone_id'), table_name='entries')
    op.drop_column('entries', 'zone_id')
    op.drop_index(op.f('ix_zone_zone_name'), table_name='zone')
    op.drop_table('zone')
    # ### end Alembic commands ###
