"""empty message

Revision ID: 27173b0a8731
Revises: 5baf8e7db0af
Create Date: 2024-12-16 01:00:06.716484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27173b0a8731'
down_revision: Union[str, None] = '5baf8e7db0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_areas_area_name'), 'main_areas', ['area_name'], unique=False)
    op.add_column('entries', sa.Column('main_area_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_entries_main_area_id'), 'entries', ['main_area_id'], unique=False)
    op.create_foreign_key(None, 'entries', 'main_areas', ['main_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_index(op.f('ix_entries_main_area_id'), table_name='entries')
    op.drop_column('entries', 'main_area_id')
    op.drop_index(op.f('ix_main_areas_area_name'), table_name='main_areas')
    op.drop_table('main_areas')
    # ### end Alembic commands ###
