"""empty message

Revision ID: bcda378d008a
Revises: 1b6be11e5cf2
Create Date: 2024-12-16 20:11:53.226668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcda378d008a'
down_revision: Union[str, None] = '1b6be11e5cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_area_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_main_area_id'), 'users', ['main_area_id'], unique=False)
    op.create_index(op.f('ix_users_zone_id'), 'users', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'users', 'zone', ['zone_id'], ['id'])
    op.create_foreign_key(None, 'users', 'main_areas', ['main_area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_zone_id'), table_name='users')
    op.drop_index(op.f('ix_users_main_area_id'), table_name='users')
    op.drop_column('users', 'zone_id')
    op.drop_column('users', 'main_area_id')
    # ### end Alembic commands ###
